type: http
name: List application documents
url: '{{baseUrl}}/applications/:applicationId/documents'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          [
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "1984-05-25T03:38:05.972Z",
              "verificationStatus": "verified"
            },
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "2009-08-26T17:56:36.937Z",
              "verificationStatus": "verified"
            }
          ]
      headers:
        - key: Content-Type
          value: application/json
    name: List of documents
